//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/awp_4one.html
halflife.wad
cstrike.wad
cs_dust.wad
de_piranesi.wad
gfx/env/morningdewbk.tga
gfx/env/morningdewdn.tga
gfx/env/morningdewft.tga
gfx/env/morningdewlf.tga
gfx/env/morningdewrt.tga
gfx/env/morningdewup.tga
de_aztec.wad
cs_havana.wad
maps/awp_4one.bsp
maps/awp_4one.txt
