maps/gg_halloween.bsp
maps/gg_halloween.res
maps/gg_halloween.txt
gfx/env/cxbk.tga
gfx/env/cxdn.tga
gfx/env/cxft.tga
gfx/env/cxrt.tga
gfx/env/cxup.tga
gfx/env/cxlf.tga
models/pumpkin_wj5.mdl
models/candle.mdl
models/churchcandle.mdl
models/17b/cm_rocks.mdl
models/17b/lampehaengt01a.mdl
models/17b1/buisson_fleur01.mdl
models/17b1/buisson16.mdl
models/17b1/bush1.mdl
models/17b1/bush02.mdl
models/17b1/bush08.mdl
models/17b1/d1.mdl
models/17b1/flo_grass4.mdl
models/17b1/tree_japan_maple_orange.mdl
models/17b1/tree_japan_maple_red.mdl
models/17b2/cc_vasa.mdl
models/de_christmas_on_a_newplanet/bush34.mdl
models/de_christmas_on_a_newplanet/bush36.mdl
models/de_christmas_on_a_newplanet/skeletonwori01.mdl
models/de_christmas_on_a_newplanet/skeletonwori05.mdl
models/de_christmas_on_a_newplanet/skeletonwori06.mdl
sound/ambience/burning3.wav
sound/halloween/Crossing_the_Threshold.wav
sprites/de_christmas_on_a_newplanet/qfire.spr